# Data Scientist Technical Test (A):

## Initial Thoughts:
- I need to create a function that takes in 2 arguments (N,M).
- N is the size of the N*N matrix.
- M is a list of lists, where each list will be a pizzerias location and delivery range.

To find the best location for Mr. Little Z to live in I'll be creating a matrix of zeros. For every block a delivery can be made to I will count. After adding all the pizzerias and their delivery locations I can just search for the largest number.

In [1]:
import numpy as np

In [2]:
#  generate a 3,3 grid:

N = 5

grid = np.zeros((N,N))
grid

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
# add pizzeria:

M = [[3,3,2],[1,1,2]]

In [4]:
# calculate manhattan distance for every element, if <= k then put 1.

In [5]:
for m in M:
    for idx, row in enumerate(grid[:,]):
        for jdx, j in enumerate(row):
            manhattan = abs(idx+1 - m[0]) + abs(jdx+1 - m[1])
            if manhattan <= m[2]:
                grid[idx, jdx] += 1
            
grid
        

array([[1., 1., 2., 0., 0.],
       [1., 2., 1., 1., 0.],
       [2., 1., 1., 1., 1.],
       [0., 1., 1., 1., 0.],
       [0., 0., 1., 0., 0.]])

In [6]:
np.rot90(grid)

array([[0., 0., 1., 0., 0.],
       [0., 1., 1., 1., 0.],
       [2., 1., 1., 1., 1.],
       [1., 2., 1., 1., 0.],
       [1., 1., 2., 0., 0.]])

In [7]:
# function to generate grid of N-N
def generate_grid(N):
    return np.zeros((N,N))

# function to calculate manhattan distance
def manhattan_distance(x1,y1,x2,y2):
    return abs(x1 - x2) + abs(y1 - y2)

# function to find the blocks each pizzeria can deliver too.
def populate_grid(grid, M):
    for m in M:
        for idx, row in enumerate(grid[:,]):
            for jdx, j in enumerate(row):
                manhattan = manhattan_distance(idx+1, jdx+1, m[0], m[1])
                if manhattan <= m[2]:
                    grid[idx, jdx] += 1       
    return grid

def rotation(grid):
    return np.rot90(grid)

def main(N, M):
    grid = generate_grid(N)
    grid = populate_grid(grid, M)
    grid = rotation(grid)
    print(grid)
    return grid.max()

In [8]:
N = 5
M = [[3,3,2],[1,1,2]]

main(N, M)

[[0. 0. 1. 0. 0.]
 [0. 1. 1. 1. 0.]
 [2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 0.]
 [1. 1. 2. 0. 0.]]


2.0