# Data Scientist Technical Test (A):

## Initial Thoughts:
- I need to create a function that takes in 2 arguments (N,M).
- N is the size of the N*N matrix.
- M is a list of lists, where each list will be a pizzerias location and delivery range.

To find the best location for Mr. Little Z to live in I'll be creating a matrix of zeros. For every block a delivery can be made to I will count. After adding all the pizzerias and their delivery locations I can just search for the largest number.

In [1]:
import numpy as np

In [2]:
def generate_grid(N):
    """
    Creates a N-N Matrix of zeros
    
    Args: N - The size of the N by N Matrix 
    
    Returns: An N by N matrix of zeros
    """
    return np.zeros((N,N))

def manhattan_distance(x1,y1,x2,y2):
    """
    Calculates the manhattan distance between two 2d arrays
    
    Args: x1 - x position of grid cell
          x2 - x position of the pizzeria
          y1 - y position of gird cell
          y2 - y position of the pizzeria
          
    Returns: The manhattan distance between the grid cell and the pizzeria
    """
    return abs(x1 - x2) + abs(y1 - y2)

def populate_grid(grid, M):
    """
    For each pizzeria the function loops through the grid and adds 1 to any cell within its manhattan distance
    
    Args: grid - the N-N matrix created in generate_grid
          M - a list of all the pizzerias and their respective locations and deliver distances
    
    Returns: A grid where each cell is the number of pizzerias that can deliver there.
    """
    # loops through the list of pizzerias
    for m in M:
        # loops through each cell in the grid
        for idx, row in enumerate(grid[:,]):
            for jdx, j in enumerate(row):
                # calculates the manhattan distance between the current cell and the current pizzeria
                manhattan = manhattan_distance(idx+1, jdx+1, m[0], m[1])
                # if the distance is <= to the manhattan distance the cell can be delivered to
                if manhattan <= m[2]:
                    grid[idx, jdx] += 1       
    return grid

def rotation(grid):
    """
    rotates the grid by 90 degrees anticlockwise to have the axes match the question
    
    Args: the grid after populate_grid has been applied
    
    Returns: the grid in an orientation that matches the questions axes and origin   
    """
    return np.rot90(grid)

def main(N, M, print_grid=False):
    """
    used to control the flow of processes
    
    Args: N - the size of the N-N matrix
          M - a list of all the pizzerias with their respective location and delivery range ([X,Y,K])
          pring_grid - a bool used to print the final matrix (after all the above operations)
    
    Returns: the value of the cell(s) that have the maximum pizzerias available for delivery. If pring_grid = True,
             the function will print the final grid.
    """
    grid = generate_grid(N)
    grid = populate_grid(grid, M)
    grid = rotation(grid)
    if print_grid:
        print(grid)
    return grid.max()

In [3]:
# Used to test some very basic functionalities of the code above:
# all conditions have been checked manually.

def test():
    assert main(5, [[3,3,2],[1,1,2]], print_grid=True) >= 0
    assert main(5, [[3,3,2],[1,1,2]]) == 2
    assert main(10, [[7, 5, 4],[3, 5, 5],[4, 8, 4],[1, 7, 6]]) == 4
    assert main(19, [[5, 14, 14],[10, 17, 2],[17, 15, 8]]) == 3
    
test()

[[0. 0. 1. 0. 0.]
 [0. 1. 1. 1. 0.]
 [2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 0.]
 [1. 1. 2. 0. 0.]]
